In [1]:
import pickle
import pandas as pd
import numpy as np

In [2]:
model = pickle.load(open('model.sav', 'rb'))
model

RandomForestRegressor(n_jobs=2, random_state=0)

In [3]:
import pandas as pd
df = pd.read_csv('./opening_prices_biotech_complete.csv')
df.head()

,Unnamed: 0,ticker,2015-12-22,2015-12-23,2015-12-24,2015-12-28,2015-12-29,2015-12-30,2015-12-31,2016-01-04,...,2019-12-17,2019-12-18,2019-12-19,2019-12-20,2019-12-23,2019-12-24,2019-12-26,2019-12-27,2019-12-30,2019-12-31
0,0,NVO,49.0179,49.5701,49.7771,50.2947,50.4069,50.6312,50.2947,49.8548,...,54.9628,54.4045,54.1207,54.8965,54.8965,54.6221,54.8397,55.4642,55.275,54.5748
1,1,VRTX,121.0900,123.9200,124.3800,123.9900,124.9700,127.6800,125.5500,123.0300,...,219.7200,217.8300,220.1400,219.6200,220.9500,220.4600,220.6000,220.5900,220.380,218.6000
2,2,REGN,535.5900,531.0600,535.5600,536.4500,542.2800,550.5400,542.6200,531.7600,...,375.7300,370.3000,371.9500,374.9400,377.2000,374.7500,376.7600,375.2400,373.740,373.6400
3,4,SGEN,42.3100,42.7300,43.7100,43.7000,44.5100,45.3000,44.8200,43.8800,...,115.2000,113.9600,118.5000,115.0000,118.3200,115.2100,115.1700,113.7300,113.690,113.9000
4,5,ALNY,88.2700,87.2400,91.2900,90.1600,92.4900,93.4800,94.1800,92.1800,...,123.7000,117.2700,116.1000,117.8800,115.7400,117.0800,118.0000,118.3000,116.830,114.0000

In [4]:
df = df.drop(['ticker', 'Unnamed: 0'], axis = 1)

In [5]:
prices = df[df.columns[100:150]]
prices

,2016-05-17,2016-05-18,2016-05-19,2016-05-20,2016-05-23,2016-05-24,2016-05-25,2016-05-26,2016-05-27,2016-05-31,...,2016-07-14,2016-07-15,2016-07-18,2016-07-19,2016-07-20,2016-07-21,2016-07-22,2016-07-25,2016-07-26,2016-07-27
0,47.6395,47.5868,47.4464,47.4113,47.2006,47.5605,49.6410,49.0967,48.6666,48.7719,...,48.7895,48.4735,48.4822,48.4296,48.3681,48.0697,48.6051,48.5963,49.4829,49.0265
1,81.4600,80.2700,80.8900,81.0300,84.2800,83.7000,88.9900,89.0500,89.2800,90.6200,...,88.9800,89.3400,90.0600,89.0800,87.3000,91.3400,93.6300,93.5100,95.9000,94.6500
2,392.9900,386.0400,387.1200,383.3700,386.4600,397.2300,399.9500,393.4900,398.4900,398.3600,...,367.0200,367.8800,374.8000,381.5300,377.4800,386.2500,391.4000,391.0300,393.0000,399.6400
3,34.1300,35.7600,37.7900,38.0900,38.8400,39.7800,40.2200,40.3400,39.6500,40.2500,...,41.6800,42.1000,43.0000,42.0000,41.9700,43.6900,44.3100,44.1400,44.1800,42.6500
4,54.0800,53.6500,54.0200,53.9400,55.1200,56.8600,58.2300,66.1500,69.9600,68.2800,...,63.4300,63.1600,64.3200,64.7300,64.2800,66.3200,65.2400,65.6400,66.3000,66.9800
5,85.7300,83.5400,86.4600,84.9400,86.8500,86.3200,88.3100,88.0400,87.5700,89.3500,...,88.1900,89.7900,92.2300,93.4900,91.5700,92.0000,93.7800,94.0200,93.2700,91.5800
6,76.0700,75.1800,76.9900,76.3400,77.9700,81.1000,81.3100,82.6300,81.6900,84.9900,...,83.3100,82.8500,84.1900,83.7400,82.9100,87.1800,88.4700,86.6000,86.0100,87.6700
7,98.9017,97.7034,97.9526,99.3235,100.3205,101.2599,102.4103,102.5636,102.5061,105.4204,...,109.7629,107.2130,106.6666,106.6282,106.4077,107.1363,106.6091,106.4077,105.6792,105.7079
8,109.9500,110.2100,111.9700,111.0200,113.7800,114.0000,117.8300,117.5000,116.9800,118.3700,...,110.5800,111.0000,111.0100,111.0700,112.0000,115.2500,113.0000,111.6500,111.7500,112.5200
9,148.9800,149.3500,150.6400,147.7400,150.3100,149.8900,151.5000,153.3800,152.7000,151.9400,...,143.1800,142.4300,142.0200,142.7900,141.8700,143.4700,143.4700,142.0200,140.9800,139.4400
10,17.5400,17.1900,17.0000,18.5000,19.3800,18.2900,22.1500,23.1600,22.2500,21.8400,...,21.4000,20.2300,20.9300,21.2000,20.8600,22.5200,22.9100,24.0300,23.4100,24.5900
11,32.4800,32.4900,33.3500,33.0600,33.3500,34.3100,33.6900,26.8000,20.1800,22.2900,...,24.8400,24.5900,27.3500,28.0000,26.8400,27.6400,27.9000,27.8500,28.2700,28.3600
12,5.4900,5.2400,5.3500,5.3900,5.8100,6.1000,6.2000,6.2300,6.3400,6.4000,...,8.1100,8.2900,8.3600,8.3500,8.3600,8.5600,8.6700,8.6800,8.6900,8.6600
13,9.0000,8.8000,9.0000,8.9600,9.1500,9.4200,9.8300,10.0500,9.9000,9.9600,...,8.6900,8.6700,8.8900,8.9800,8.7900,9.2900,9.3500,9.3000,9.2600,9.6200
14,7.6500,7.3600,7.5700,7.5700,7.6400,7.8100,8.1100,8.2000,8.0800,8.1600,...,9.9100,9.7700,9.9200,9.7600,9.5600,9.8000,9.9400,9.8500,9.8400,9.9700
15,14.5700,14.6700,14.8700,13.9600,14.0000,14.0600,13.9600,13.9600,13.7601,14.0000,...,12.6111,12.8600,12.9400,12.8400,12.9000,13.2100,13.2400,12.8500,12.8900,13.0000
16,19.3800,18.2200,19.1600,20.6200,20.6900,20.5800,21.5400,22.0600,22.2800,23.4100,...,17.3100,16.5500,16.6200,18.0600,18.6400,18.7500,18.2800,17.9600,17.2200,17.1400
17,15.5100,15.5900,15.7200,15.6500,16.0000,16.8600,17.6100,17.8200,17.4900,18.0600,...,5.3100,5.1000,5.2600,5.3400,5.0200,5.1000,5.1200,5.0900,4.9200,4.7400
18,15.8700,16.3100,16.4000,17.4700,17.9900,17.9100,18.4600,18.2300,18.4100,18.3000,...,20.4800,20.3100,20.3500,20.6000,20.1900,21.1200,21.4700,21.4900,21.6600,21.5800
19,5.1400,4.8800,5.1500,5.1000,5.4800,5.6800,5.7800,5.9400,5.8400,5.9300,...,5.6500,5.5800,5.8000,5.8800,5.6100,5.7400,5.5800,5.6500,5.6400,5.7600
20,7.1400,6.9300,6.8100,6.7700,8.0100,7.8100,8.3700,8.3300,7.7600,7.9300,...,7.1100,6.9300,7.1300,7.1000,6.8900,7.5100,7.3100,7.2200,6.3800,5.9000
21,4.0600,3.8500,4.8000,4.4100,4.3700,4.3800,4.3800,4.5200,4.4100,5.1900,...,4.6800,4.5500,4.5300,4.7500,4.5300,4.6600,4.6600,4.6200,4.4400,4.5700
22,59.1700,58.4400,62.8700,61.3500,64.0900,65.9500,68.5400,68.3900,69.1200,69.7200,...,52.1900,51.1400,53.4600,53.3500,50.8000,53.0000,52.7100,53.9300,53.9500,57.4900
23,51.0900,51.1600,51.0500,53.4600,57.6500,56.2300,58.9400,58.1800,57.7500,57.5500,...,54.0100,52.5700,53.5000,52.9800,52.8400,52.2300,52.3600,52.4300,53.5100,53.4000
24,10.9900,10.7900,10.9400,10.9000,11.1900,11.4900,11.9000,11.9900,11.9400,11.6400,...,11.2300,11.1300,11.4000,11.3900,10.9100,11.2100,11.1900,11.0900,11.0100,10.9500
25,29.9300,31.4400,32.2700,32.9800,33.9800,34.5300,35.2800,35.0500,34.9000,36.2100,...,33.3100,32.7200,33.0000,33.1600,33.1800,35.6000,36.3500,36.6300,36.1300,36.9200
26,3.0500,3.0400,3.0700,3.1400,3.3200,3.2500,3.4000,3.3500,3.3600,3.4000,...,2.9600,2.9000,2.9600,3.0100,2.9000,3.0000,2.9900,3.0800,3.0300,3.0200
27,93.6000,96.8000,102.4000,102.2000,105.4000,108.8000,118.0000,115.4000,112.8000,119.6000,...,149.6000,152.4000,151.6000,151.6000,145.4000,149.8000,147.6000,147.0000,146.6000,148.4000
28,50.2100,53.4300,50.1400,45.0500,45.4400,49.3300,48.7200,52.7900,52.8300,53.9200,...,41.3800,41.1300,41.7500,41.6500,40.0800,42.7300,43.1300,42.2300,41.9900,43.9800
29,43.1500,47.1500,51.0500,49.1000,52.0500,55.1500,54.7500,54.4500,56.3000,59.0000,...,63.1000,62.9500,65.5000,66.7000,63.4000,67.0000,68.4000,69.9000,70.4500,71.8000
30,24.3100,23.4800,23.6500,23.1600,23.6000,23.6800,24.2700,23.6200,23.1600,24.3900,...,22.3200,22.0000,22.0300,21.9100,21.3500,21.6300,22.8300,22.1900,21.7000,21.7000
31,12.3000,12.4100,12.2350,12.0100,11.9900,12.0000,11.7400,12.3400,12.3800,12.6800,...,7.7100,7.5200,7.9000,7.6800,7.3800,7.5600,7.9100,7.9700,7.7500,7.8500
32,42.4800,40.8800,41.4500,40.9600,43.0800,44.7200,46.5200,48.0300,46.4000,47.0900,...,44.6600,45.8900,48.8300,49.8800,49.1100,52.7000,53.7400,53.3600,51.8500,52.1000
33,5.6300,5.5100,5.5500,5.4800,5.5300,5.6400,5.8100,5.8900,5.6600,5.6200,...,2.8500,2.7600,2.7700,3.0500,2.8100,3.0500,2.8500,2.8700,2.8000,2.8200
34,13.5800,13.4050,12.6350,12.8240,12.9500,13.3000,12.7750,12.9500,13.2510,12.9500,...,9.8000,9.4500,9.4500,9.4500,9.1000,9.8000,9.7300,8.3500,10.0000,8.5300
35,17.5600,17.2500,17.9400,17.6000,18.1900,18.2200,18.2200,18.6000,18.3900,18.4500,...,17.0300,16.6800,17.1500,17.4000,17.0000,17.7700,18.0400,17.5800,17.6500,18.4100
36,46.0600,46.7900,47.3500,47.7800,48.4300,50.9900,51.5100,50.9200,51.1600,51.6600,...,54.3300,55.8700,58.4100,58.3600,58.3800,62.2700,63.4700,64.4500,63.0000,64.4300
37,3.2200,3.0387,3.0700,3.2299,3.2400,3.1100,3.0700,3.0600,2.9700,2.9200,...,3.7800,5.2000,4.9400,4.4200,4.2100,4.4000,4.3500,4.3200,4.2300,4.0600
38,12.7100,12.6600,12.6100,12.1100,12.0600,12.2800,12.4700,12.4500,12.3500,12.2400,...,7.7400,7.3400,7.5400,7.5700,7.1400,7.1900,7.3700,7.1700,7.0200,7.0500
39,5.9300,6.0000,6.0900,6.0500,6.2700,6.3800,6.5400,6.7500,6.5600,6.7400,...,5.7800,5.6100,5.7100,5.7400,5.4700,5.6800,5.8600,5.7900,5.7200,5.8800
40,4.0200,4.1300,4.0500,4.3000,4.5100,4.4800,4.4500,4.4400,4.4100,4.4100,...,7.0000,6.8000,7.0500,7.4100,7.0500,7.1200,7.1000,7.4500,7.5400,7.5500
41,24.8200,25.0900,27.0000,27.6900,29.0400,29.0300,30.0000,28.6900,29.1800,29.6600,...,31.9900,32.3800,33.0000,33.4000,33.2900,33.6000,33.9000,34.1700,33.6900,35.0000
42,134.5500,132.2300,133.4600,131.6900,134.8500,139.0000,140.0200,142.2000,139.9500,137.8000,...,146.1400,145.5000,148.5300,149.2300,146.0900,149.6000,152.3300,157.7800,157.8300,159.8700
43,22.8642,23.0611,23.3654,23.2282,24.3081,25.6029,25.3642,26.3129,26.2115,26.6292,...,28.0671,27.2497,27.4287,27.6614,27.1542,29.5349,29.1292,29.3261,29.0397,30.1793
44,3.4900,3.3600,3.4899,3.4500,3.5700,3.7300,3.9500,3.9900,4.0700,4.0500,...,4.1300,4.2200,4.1400,4.1700,4.1100,4.1500,4.0900,4.1100,4.0500,4.0800
45,7.9800,7.9500,8.1100,8.1800,8.5200,8.8000,9.5100,9.6900,9.7100,9.7200,...,7.2700,7.2400,7.4400,7.5800,7.1500,7.1700,7.1800,7.0700,7.0800,7.4000
46,10.8100,11.0900,10.9200,11.8000,11.8000,12.1700,12.8900,12.7900,12.8900,13.8000,...,11.9400,12.3300,12.7100,12.5600,12.5000,12.7100,12.7600,13.9100,13.6500,14.3000
47,93.2800,93.9200,97.1200,96.8000,96.4800,97.9200,96.9600,96.6400,96.8000,98.8800,...,67.0400,65.6000,66.4000,66.5600,64.9600,68.1600,72.0000,70.4000,67.2000,60.6400

In [7]:
new = pd.DataFrame()
new["std"] = df.std()
new["min"] = df.min()
new["max"] = df.max()
new["mean"] = df.mean()
new = new.reset_index()

In [8]:
new

           index        std   min     max       mean
0     2015-12-22  91.438335  3.94  535.59  67.080625
1     2015-12-23  89.526144  3.94  531.06  66.018810
2     2015-12-24  90.863732  3.96  535.56  66.942758
3     2015-12-28  91.285993  3.99  536.45  66.933475
4     2015-12-29  92.350122  4.03  542.28  67.351583
...          ...        ...   ...     ...        ...
1008  2019-12-24  73.458227  2.53  374.75  69.519669
1009  2019-12-26  73.489159  2.55  376.76  69.838165
1010  2019-12-27  73.340423  2.84  375.24  69.787054
1011  2019-12-30  73.031301  2.55  373.74  68.861387
1012  2019-12-31  72.804462  2.36  373.64  68.205917

[1013 rows x 5 columns]